// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.github.begoodyourself.api.protos;

public final class ProtobufRpcMessage {
  private ProtobufRpcMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcRequestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RpcRequestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string messageId = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <code>optional string messageId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>optional string requestService = 2;</code>
     */
    java.lang.String getRequestService();
    /**
     * <code>optional string requestService = 2;</code>
     */
    com.google.protobuf.ByteString
        getRequestServiceBytes();

    /**
     * <code>optional string requestMethod = 3;</code>
     */
    java.lang.String getRequestMethod();
    /**
     * <code>optional string requestMethod = 3;</code>
     */
    com.google.protobuf.ByteString
        getRequestMethodBytes();

    /**
     * <code>optional string requestParameterProto = 4;</code>
     */
    java.lang.String getRequestParameterProto();
    /**
     * <code>optional string requestParameterProto = 4;</code>
     */
    com.google.protobuf.ByteString
        getRequestParameterProtoBytes();

    /**
     * <code>optional bytes requestBody = 5;</code>
     */
    com.google.protobuf.ByteString getRequestBody();
  }
  /**
   * <pre>
   * [END java_declaration]
   * </pre>
   *
   * Protobuf type {@code RpcRequestProto}
   */
  public  static final class RpcRequestProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RpcRequestProto)
      RpcRequestProtoOrBuilder {
    // Use RpcRequestProto.newBuilder() to construct.
    private RpcRequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcRequestProto() {
      messageId_ = "";
      requestService_ = "";
      requestMethod_ = "";
      requestParameterProto_ = "";
      requestBody_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RpcRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              requestService_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              requestMethod_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              requestParameterProto_ = s;
              break;
            }
            case 42: {

              requestBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.begoodyourself.api.protos.ProtobufRpcMessage.internal_static_RpcRequestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.begoodyourself.api.protos.ProtobufRpcMessage.internal_static_RpcRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto.class, com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageId_;
    /**
     * <code>optional string messageId = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string messageId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTSERVICE_FIELD_NUMBER = 2;
    private volatile java.lang.Object requestService_;
    /**
     * <code>optional string requestService = 2;</code>
     */
    public java.lang.String getRequestService() {
      java.lang.Object ref = requestService_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestService_ = s;
        return s;
      }
    }
    /**
     * <code>optional string requestService = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRequestServiceBytes() {
      java.lang.Object ref = requestService_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestService_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTMETHOD_FIELD_NUMBER = 3;
    private volatile java.lang.Object requestMethod_;
    /**
     * <code>optional string requestMethod = 3;</code>
     */
    public java.lang.String getRequestMethod() {
      java.lang.Object ref = requestMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestMethod_ = s;
        return s;
      }
    }
    /**
     * <code>optional string requestMethod = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRequestMethodBytes() {
      java.lang.Object ref = requestMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTPARAMETERPROTO_FIELD_NUMBER = 4;
    private volatile java.lang.Object requestParameterProto_;
    /**
     * <code>optional string requestParameterProto = 4;</code>
     */
    public java.lang.String getRequestParameterProto() {
      java.lang.Object ref = requestParameterProto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestParameterProto_ = s;
        return s;
      }
    }
    /**
     * <code>optional string requestParameterProto = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRequestParameterProtoBytes() {
      java.lang.Object ref = requestParameterProto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestParameterProto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTBODY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString requestBody_;
    /**
     * <code>optional bytes requestBody = 5;</code>
     */
    public com.google.protobuf.ByteString getRequestBody() {
      return requestBody_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (!getRequestServiceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestService_);
      }
      if (!getRequestMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, requestMethod_);
      }
      if (!getRequestParameterProtoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, requestParameterProto_);
      }
      if (!requestBody_.isEmpty()) {
        output.writeBytes(5, requestBody_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (!getRequestServiceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestService_);
      }
      if (!getRequestMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, requestMethod_);
      }
      if (!getRequestParameterProtoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, requestParameterProto_);
      }
      if (!requestBody_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, requestBody_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto)) {
        return super.equals(obj);
      }
      com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto other = (com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto) obj;

      boolean result = true;
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && getRequestService()
          .equals(other.getRequestService());
      result = result && getRequestMethod()
          .equals(other.getRequestMethod());
      result = result && getRequestParameterProto()
          .equals(other.getRequestParameterProto());
      result = result && getRequestBody()
          .equals(other.getRequestBody());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + REQUESTSERVICE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestService().hashCode();
      hash = (37 * hash) + REQUESTMETHOD_FIELD_NUMBER;
      hash = (53 * hash) + getRequestMethod().hashCode();
      hash = (37 * hash) + REQUESTPARAMETERPROTO_FIELD_NUMBER;
      hash = (53 * hash) + getRequestParameterProto().hashCode();
      hash = (37 * hash) + REQUESTBODY_FIELD_NUMBER;
      hash = (53 * hash) + getRequestBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [END java_declaration]
     * </pre>
     *
     * Protobuf type {@code RpcRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RpcRequestProto)
        com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.begoodyourself.api.protos.ProtobufRpcMessage.internal_static_RpcRequestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.begoodyourself.api.protos.ProtobufRpcMessage.internal_static_RpcRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto.class, com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto.Builder.class);
      }

      // Construct using com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = "";

        requestService_ = "";

        requestMethod_ = "";

        requestParameterProto_ = "";

        requestBody_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.begoodyourself.api.protos.ProtobufRpcMessage.internal_static_RpcRequestProto_descriptor;
      }

      public com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto getDefaultInstanceForType() {
        return com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto.getDefaultInstance();
      }

      public com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto build() {
        com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto buildPartial() {
        com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto result = new com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto(this);
        result.messageId_ = messageId_;
        result.requestService_ = requestService_;
        result.requestMethod_ = requestMethod_;
        result.requestParameterProto_ = requestParameterProto_;
        result.requestBody_ = requestBody_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto) {
          return mergeFrom((com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto other) {
        if (other == com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto.getDefaultInstance()) return this;
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (!other.getRequestService().isEmpty()) {
          requestService_ = other.requestService_;
          onChanged();
        }
        if (!other.getRequestMethod().isEmpty()) {
          requestMethod_ = other.requestMethod_;
          onChanged();
        }
        if (!other.getRequestParameterProto().isEmpty()) {
          requestParameterProto_ = other.requestParameterProto_;
          onChanged();
        }
        if (other.getRequestBody() != com.google.protobuf.ByteString.EMPTY) {
          setRequestBody(other.getRequestBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <code>optional string messageId = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string messageId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string messageId = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string messageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string messageId = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestService_ = "";
      /**
       * <code>optional string requestService = 2;</code>
       */
      public java.lang.String getRequestService() {
        java.lang.Object ref = requestService_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestService_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestService = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRequestServiceBytes() {
        java.lang.Object ref = requestService_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestService_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestService = 2;</code>
       */
      public Builder setRequestService(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestService_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestService = 2;</code>
       */
      public Builder clearRequestService() {
        
        requestService_ = getDefaultInstance().getRequestService();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestService = 2;</code>
       */
      public Builder setRequestServiceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestService_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestMethod_ = "";
      /**
       * <code>optional string requestMethod = 3;</code>
       */
      public java.lang.String getRequestMethod() {
        java.lang.Object ref = requestMethod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestMethod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestMethod = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRequestMethodBytes() {
        java.lang.Object ref = requestMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestMethod = 3;</code>
       */
      public Builder setRequestMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestMethod = 3;</code>
       */
      public Builder clearRequestMethod() {
        
        requestMethod_ = getDefaultInstance().getRequestMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestMethod = 3;</code>
       */
      public Builder setRequestMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestMethod_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestParameterProto_ = "";
      /**
       * <code>optional string requestParameterProto = 4;</code>
       */
      public java.lang.String getRequestParameterProto() {
        java.lang.Object ref = requestParameterProto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestParameterProto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestParameterProto = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRequestParameterProtoBytes() {
        java.lang.Object ref = requestParameterProto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestParameterProto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestParameterProto = 4;</code>
       */
      public Builder setRequestParameterProto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestParameterProto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestParameterProto = 4;</code>
       */
      public Builder clearRequestParameterProto() {
        
        requestParameterProto_ = getDefaultInstance().getRequestParameterProto();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestParameterProto = 4;</code>
       */
      public Builder setRequestParameterProtoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestParameterProto_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString requestBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes requestBody = 5;</code>
       */
      public com.google.protobuf.ByteString getRequestBody() {
        return requestBody_;
      }
      /**
       * <code>optional bytes requestBody = 5;</code>
       */
      public Builder setRequestBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes requestBody = 5;</code>
       */
      public Builder clearRequestBody() {
        
        requestBody_ = getDefaultInstance().getRequestBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RpcRequestProto)
    }

    // @@protoc_insertion_point(class_scope:RpcRequestProto)
    private static final com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto();
    }

    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcRequestProto>
        PARSER = new com.google.protobuf.AbstractParser<RpcRequestProto>() {
      public RpcRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RpcRequestProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcRequestProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RpcRequestProto> getParserForType() {
      return PARSER;
    }

    public com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcRequestProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RpcResponseProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RpcResponseProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string messageId = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <code>optional string messageId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>optional int32 errorcode = 2;</code>
     */
    int getErrorcode();

    /**
     * <code>optional string errormsg = 3;</code>
     */
    java.lang.String getErrormsg();
    /**
     * <code>optional string errormsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrormsgBytes();

    /**
     * <code>optional string responseProto = 4;</code>
     */
    java.lang.String getResponseProto();
    /**
     * <code>optional string responseProto = 4;</code>
     */
    com.google.protobuf.ByteString
        getResponseProtoBytes();

    /**
     * <code>optional bytes responseBody = 5;</code>
     */
    com.google.protobuf.ByteString getResponseBody();
  }
  /**
   * Protobuf type {@code RpcResponseProto}
   */
  public  static final class RpcResponseProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RpcResponseProto)
      RpcResponseProtoOrBuilder {
    // Use RpcResponseProto.newBuilder() to construct.
    private RpcResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcResponseProto() {
      messageId_ = "";
      errorcode_ = 0;
      errormsg_ = "";
      responseProto_ = "";
      responseBody_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RpcResponseProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 16: {

              errorcode_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errormsg_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              responseProto_ = s;
              break;
            }
            case 42: {

              responseBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.begoodyourself.api.protos.ProtobufRpcMessage.internal_static_RpcResponseProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.begoodyourself.api.protos.ProtobufRpcMessage.internal_static_RpcResponseProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto.class, com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto.Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageId_;
    /**
     * <code>optional string messageId = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string messageId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorcode_;
    /**
     * <code>optional int32 errorcode = 2;</code>
     */
    public int getErrorcode() {
      return errorcode_;
    }

    public static final int ERRORMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object errormsg_;
    /**
     * <code>optional string errormsg = 3;</code>
     */
    public java.lang.String getErrormsg() {
      java.lang.Object ref = errormsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errormsg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string errormsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrormsgBytes() {
      java.lang.Object ref = errormsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errormsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSEPROTO_FIELD_NUMBER = 4;
    private volatile java.lang.Object responseProto_;
    /**
     * <code>optional string responseProto = 4;</code>
     */
    public java.lang.String getResponseProto() {
      java.lang.Object ref = responseProto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseProto_ = s;
        return s;
      }
    }
    /**
     * <code>optional string responseProto = 4;</code>
     */
    public com.google.protobuf.ByteString
        getResponseProtoBytes() {
      java.lang.Object ref = responseProto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseProto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSEBODY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString responseBody_;
    /**
     * <code>optional bytes responseBody = 5;</code>
     */
    public com.google.protobuf.ByteString getResponseBody() {
      return responseBody_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (errorcode_ != 0) {
        output.writeInt32(2, errorcode_);
      }
      if (!getErrormsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errormsg_);
      }
      if (!getResponseProtoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, responseProto_);
      }
      if (!responseBody_.isEmpty()) {
        output.writeBytes(5, responseBody_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (errorcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorcode_);
      }
      if (!getErrormsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errormsg_);
      }
      if (!getResponseProtoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, responseProto_);
      }
      if (!responseBody_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, responseBody_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto)) {
        return super.equals(obj);
      }
      com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto other = (com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto) obj;

      boolean result = true;
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && (getErrorcode()
          == other.getErrorcode());
      result = result && getErrormsg()
          .equals(other.getErrormsg());
      result = result && getResponseProto()
          .equals(other.getResponseProto());
      result = result && getResponseBody()
          .equals(other.getResponseBody());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorcode();
      hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrormsg().hashCode();
      hash = (37 * hash) + RESPONSEPROTO_FIELD_NUMBER;
      hash = (53 * hash) + getResponseProto().hashCode();
      hash = (37 * hash) + RESPONSEBODY_FIELD_NUMBER;
      hash = (53 * hash) + getResponseBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RpcResponseProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RpcResponseProto)
        com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.begoodyourself.api.protos.ProtobufRpcMessage.internal_static_RpcResponseProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.begoodyourself.api.protos.ProtobufRpcMessage.internal_static_RpcResponseProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto.class, com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto.Builder.class);
      }

      // Construct using com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = "";

        errorcode_ = 0;

        errormsg_ = "";

        responseProto_ = "";

        responseBody_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.begoodyourself.api.protos.ProtobufRpcMessage.internal_static_RpcResponseProto_descriptor;
      }

      public com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto getDefaultInstanceForType() {
        return com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto.getDefaultInstance();
      }

      public com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto build() {
        com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto buildPartial() {
        com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto result = new com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto(this);
        result.messageId_ = messageId_;
        result.errorcode_ = errorcode_;
        result.errormsg_ = errormsg_;
        result.responseProto_ = responseProto_;
        result.responseBody_ = responseBody_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto) {
          return mergeFrom((com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto other) {
        if (other == com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto.getDefaultInstance()) return this;
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.getErrorcode() != 0) {
          setErrorcode(other.getErrorcode());
        }
        if (!other.getErrormsg().isEmpty()) {
          errormsg_ = other.errormsg_;
          onChanged();
        }
        if (!other.getResponseProto().isEmpty()) {
          responseProto_ = other.responseProto_;
          onChanged();
        }
        if (other.getResponseBody() != com.google.protobuf.ByteString.EMPTY) {
          setResponseBody(other.getResponseBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <code>optional string messageId = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string messageId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string messageId = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string messageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string messageId = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private int errorcode_ ;
      /**
       * <code>optional int32 errorcode = 2;</code>
       */
      public int getErrorcode() {
        return errorcode_;
      }
      /**
       * <code>optional int32 errorcode = 2;</code>
       */
      public Builder setErrorcode(int value) {
        
        errorcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorcode = 2;</code>
       */
      public Builder clearErrorcode() {
        
        errorcode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errormsg_ = "";
      /**
       * <code>optional string errormsg = 3;</code>
       */
      public java.lang.String getErrormsg() {
        java.lang.Object ref = errormsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errormsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errormsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrormsgBytes() {
        java.lang.Object ref = errormsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errormsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errormsg = 3;</code>
       */
      public Builder setErrormsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errormsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errormsg = 3;</code>
       */
      public Builder clearErrormsg() {
        
        errormsg_ = getDefaultInstance().getErrormsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errormsg = 3;</code>
       */
      public Builder setErrormsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errormsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object responseProto_ = "";
      /**
       * <code>optional string responseProto = 4;</code>
       */
      public java.lang.String getResponseProto() {
        java.lang.Object ref = responseProto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseProto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string responseProto = 4;</code>
       */
      public com.google.protobuf.ByteString
          getResponseProtoBytes() {
        java.lang.Object ref = responseProto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseProto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string responseProto = 4;</code>
       */
      public Builder setResponseProto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseProto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseProto = 4;</code>
       */
      public Builder clearResponseProto() {
        
        responseProto_ = getDefaultInstance().getResponseProto();
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseProto = 4;</code>
       */
      public Builder setResponseProtoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseProto_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString responseBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes responseBody = 5;</code>
       */
      public com.google.protobuf.ByteString getResponseBody() {
        return responseBody_;
      }
      /**
       * <code>optional bytes responseBody = 5;</code>
       */
      public Builder setResponseBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes responseBody = 5;</code>
       */
      public Builder clearResponseBody() {
        
        responseBody_ = getDefaultInstance().getResponseBody();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RpcResponseProto)
    }

    // @@protoc_insertion_point(class_scope:RpcResponseProto)
    private static final com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto();
    }

    public static com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcResponseProto>
        PARSER = new com.google.protobuf.AbstractParser<RpcResponseProto>() {
      public RpcResponseProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RpcResponseProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcResponseProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RpcResponseProto> getParserForType() {
      return PARSER;
    }

    public com.github.begoodyourself.api.protos.ProtobufRpcMessage.RpcResponseProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcRequestProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RpcRequestProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcResponseProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RpcResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"\207\001\n\017RpcRequestProto\022\021\n\tm" +
      "essageId\030\001 \001(\t\022\026\n\016requestService\030\002 \001(\t\022\025" +
      "\n\rrequestMethod\030\003 \001(\t\022\035\n\025requestParamete" +
      "rProto\030\004 \001(\t\022\023\n\013requestBody\030\005 \001(\014\"w\n\020Rpc" +
      "ResponseProto\022\021\n\tmessageId\030\001 \001(\t\022\021\n\terro" +
      "rcode\030\002 \001(\005\022\020\n\010errormsg\030\003 \001(\t\022\025\n\rrespons" +
      "eProto\030\004 \001(\t\022\024\n\014responseBody\030\005 \001(\014B:\n$co" +
      "m.github.begoodyourself.api.protosB\022Prot" +
      "obufRpcMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RpcRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RpcRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RpcRequestProto_descriptor,
        new java.lang.String[] { "MessageId", "RequestService", "RequestMethod", "RequestParameterProto", "RequestBody", });
    internal_static_RpcResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RpcResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RpcResponseProto_descriptor,
        new java.lang.String[] { "MessageId", "Errorcode", "Errormsg", "ResponseProto", "ResponseBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
