// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalService.proto

package com.github.begoodyourself.sample.api.protos;

public final class CalServiceProto {
  private CalServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FibonacciReqProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FibonacciReqProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 input = 1;</code>
     */
    int getInput();
  }
  /**
   * <pre>
   * [END java_declaration]
   * </pre>
   *
   * Protobuf type {@code FibonacciReqProto}
   */
  public  static final class FibonacciReqProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FibonacciReqProto)
      FibonacciReqProtoOrBuilder {
    // Use FibonacciReqProto.newBuilder() to construct.
    private FibonacciReqProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FibonacciReqProto() {
      input_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FibonacciReqProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              input_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.begoodyourself.sample.api.protos.CalServiceProto.internal_static_FibonacciReqProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.begoodyourself.sample.api.protos.CalServiceProto.internal_static_FibonacciReqProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto.class, com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto.Builder.class);
    }

    public static final int INPUT_FIELD_NUMBER = 1;
    private int input_;
    /**
     * <code>optional int32 input = 1;</code>
     */
    public int getInput() {
      return input_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (input_ != 0) {
        output.writeInt32(1, input_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (input_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, input_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto)) {
        return super.equals(obj);
      }
      com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto other = (com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto) obj;

      boolean result = true;
      result = result && (getInput()
          == other.getInput());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getInput();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [END java_declaration]
     * </pre>
     *
     * Protobuf type {@code FibonacciReqProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FibonacciReqProto)
        com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.begoodyourself.sample.api.protos.CalServiceProto.internal_static_FibonacciReqProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.begoodyourself.sample.api.protos.CalServiceProto.internal_static_FibonacciReqProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto.class, com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto.Builder.class);
      }

      // Construct using com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        input_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.begoodyourself.sample.api.protos.CalServiceProto.internal_static_FibonacciReqProto_descriptor;
      }

      public com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto getDefaultInstanceForType() {
        return com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto.getDefaultInstance();
      }

      public com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto build() {
        com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto buildPartial() {
        com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto result = new com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto(this);
        result.input_ = input_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto) {
          return mergeFrom((com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto other) {
        if (other == com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto.getDefaultInstance()) return this;
        if (other.getInput() != 0) {
          setInput(other.getInput());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int input_ ;
      /**
       * <code>optional int32 input = 1;</code>
       */
      public int getInput() {
        return input_;
      }
      /**
       * <code>optional int32 input = 1;</code>
       */
      public Builder setInput(int value) {
        
        input_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 input = 1;</code>
       */
      public Builder clearInput() {
        
        input_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:FibonacciReqProto)
    }

    // @@protoc_insertion_point(class_scope:FibonacciReqProto)
    private static final com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto();
    }

    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FibonacciReqProto>
        PARSER = new com.google.protobuf.AbstractParser<FibonacciReqProto>() {
      public FibonacciReqProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FibonacciReqProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FibonacciReqProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FibonacciReqProto> getParserForType() {
      return PARSER;
    }

    public com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciReqProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FibonacciRespProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FibonacciRespProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 result = 1;</code>
     */
    long getResult();
  }
  /**
   * Protobuf type {@code FibonacciRespProto}
   */
  public  static final class FibonacciRespProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FibonacciRespProto)
      FibonacciRespProtoOrBuilder {
    // Use FibonacciRespProto.newBuilder() to construct.
    private FibonacciRespProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FibonacciRespProto() {
      result_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FibonacciRespProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              result_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.begoodyourself.sample.api.protos.CalServiceProto.internal_static_FibonacciRespProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.begoodyourself.sample.api.protos.CalServiceProto.internal_static_FibonacciRespProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto.class, com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private long result_;
    /**
     * <code>optional int64 result = 1;</code>
     */
    public long getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0L) {
        output.writeInt64(1, result_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, result_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto)) {
        return super.equals(obj);
      }
      com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto other = (com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto) obj;

      boolean result = true;
      result = result && (getResult()
          == other.getResult());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getResult());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FibonacciRespProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FibonacciRespProto)
        com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.begoodyourself.sample.api.protos.CalServiceProto.internal_static_FibonacciRespProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.begoodyourself.sample.api.protos.CalServiceProto.internal_static_FibonacciRespProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto.class, com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto.Builder.class);
      }

      // Construct using com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        result_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.begoodyourself.sample.api.protos.CalServiceProto.internal_static_FibonacciRespProto_descriptor;
      }

      public com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto getDefaultInstanceForType() {
        return com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto.getDefaultInstance();
      }

      public com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto build() {
        com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto buildPartial() {
        com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto result = new com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto(this);
        result.result_ = result_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto) {
          return mergeFrom((com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto other) {
        if (other == com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto.getDefaultInstance()) return this;
        if (other.getResult() != 0L) {
          setResult(other.getResult());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long result_ ;
      /**
       * <code>optional int64 result = 1;</code>
       */
      public long getResult() {
        return result_;
      }
      /**
       * <code>optional int64 result = 1;</code>
       */
      public Builder setResult(long value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:FibonacciRespProto)
    }

    // @@protoc_insertion_point(class_scope:FibonacciRespProto)
    private static final com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto();
    }

    public static com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FibonacciRespProto>
        PARSER = new com.google.protobuf.AbstractParser<FibonacciRespProto>() {
      public FibonacciRespProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FibonacciRespProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FibonacciRespProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FibonacciRespProto> getParserForType() {
      return PARSER;
    }

    public com.github.begoodyourself.sample.api.protos.CalServiceProto.FibonacciRespProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FibonacciReqProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FibonacciReqProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FibonacciRespProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FibonacciRespProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020CalService.proto\"\"\n\021FibonacciReqProto\022" +
      "\r\n\005input\030\001 \001(\005\"$\n\022FibonacciRespProto\022\016\n\006" +
      "result\030\001 \001(\003B>\n+com.github.begoodyoursel" +
      "f.sample.api.protosB\017CalServiceProtob\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FibonacciReqProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FibonacciReqProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FibonacciReqProto_descriptor,
        new java.lang.String[] { "Input", });
    internal_static_FibonacciRespProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FibonacciRespProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FibonacciRespProto_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
